version: 0.2

phases:
  pre_build:
    commands:
      - echo "Nothing in pre_build"
  build:
    commands:
      - echo "Zipping source"
      - zip -r build.zip .
artifacts:
  files:
    - build.zip
